handlers:
- url: /
  static_files: modules/lib/mavelous_web/index.html
  upload: modules/lib/mavelous_web/
- url: /(.*)
  static_files: modules/lib/mavelous_web/\1
  upload: modules/lib/mavelous_web/(.*)
